# Generated by Django 3.2.2 on 2021-05-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('accno', models.CharField(max_length=64)),
                ('acctype', models.CharField(max_length=64)),
                ('mail', models.CharField(max_length=64)),
                ('cbal', models.FloatField()),
            ],
        ),
    ]
